version: '3.8'

services:
  # Python Flask Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=suggestlyg4plus_quantum_ultra_premium_secret_2025
    volumes:
      - ./suggestly_v3.db:/app/suggestly_v3.db
    restart: unless-stopped

  # Node.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
