name: Deploy Frontend to Vercel

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:  # Allow manual deployment

# Prevent overlapping deployments
concurrency:
  group: deploy-vercel-${{ github.ref }}
  cancel-in-progress: false  # Don't cancel deployments

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    # Only run on main branch or tags, not on PRs from forks
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    
    # Minimal permissions for deployment
    permissions:
      contents: read
      id-token: write  # For OIDC with Vercel if configured
      
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build project
        run: yarn build
        env:
          CI: false
          DISABLE_ESLINT_PLUGIN: true
          # Add production environment variables here
          # REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          
      - name: Deploy to Vercel
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./