name: Deploy (Matrix)

on:
  workflow_dispatch:
  push:
    branches: [ main, "release/**" ]

jobs:
  render:
    if: ${{ secrets.RENDER_API_KEY != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

  flyio:
    if: ${{ secrets.FLY_API_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: |
          flyctl auth token $FLY_API_TOKEN
          flyctl deploy --remote-only --now
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  cloudflare:
    if: ${{ secrets.CLOUDFLARE_API_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish Worker
        run: |
          npm install -g wrangler
          wrangler publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  railway:
    if: ${{ secrets.RAILWAY_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Railway
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          railway up --service=$RAILWAY_SERVICE --ci
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE: ${{ secrets.RAILWAY_SERVICE }}


