name: Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel Project Settings
        if: ${{ env.VERCEL_TOKEN != '' }}
        run: vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}

      - name: Build
        if: ${{ env.VERCEL_TOKEN != '' }}
        run: vercel build --prod --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy
        if: ${{ env.VERCEL_TOKEN != '' }}
        run: vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

