name: Deploy Backend to Render

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "requirements.txt"
      - "render.yaml"
      - ".github/workflows/deploy-backend-render.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    name: Render Blueprint Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Render
        shell: bash
        run: |
          set -euo pipefail
          RENDER_API_KEY='${{ secrets.RENDER_API_KEY }}'
          RENDER_SERVICE_ID='${{ secrets.RENDER_SERVICE_ID }}'
          RENDER_DEPLOY_HOOK_URL='${{ secrets.RENDER_DEPLOY_HOOK_URL }}'
          if [[ -n "${RENDER_DEPLOY_HOOK_URL:-}" ]]; then
            echo "Triggering Render deploy via Deploy Hook"
            curl -fsSL -X POST "$RENDER_DEPLOY_HOOK_URL"
            exit 0
          fi
          if [[ -n "${RENDER_API_KEY:-}" && -n "${RENDER_SERVICE_ID:-}" ]]; then
            echo "Triggering Render deploy via API"
            curl -fsSL -X POST \
              -H "Authorization: Bearer $RENDER_API_KEY" \
              -H "Content-Type: application/json" \
              "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
              -d '{}'
            exit 0
          fi
          echo "No Render deployment method configured. Set RENDER_DEPLOY_HOOK_URL or both RENDER_API_KEY and RENDER_SERVICE_ID as secrets."


