name: Deploy Matrix (Experimental)

# Only allow manual deployment for experimental features
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - dev
        - testing

# Prevent overlapping deployments
concurrency:
  group: deploy-matrix-${{ github.ref }}-${{ github.event.inputs.environment }}
  cancel-in-progress: false

jobs:
  deploy-matrix:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    # Only allow deployment from main branch
    if: github.ref == 'refs/heads/main'
    
    # Minimal permissions
    permissions:
      contents: read
      id-token: write  # For OIDC authentication
      
    environment:
      name: ${{ github.event.inputs.environment }}
      
    strategy:
      matrix:
        target: [frontend, storybook]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build frontend
        if: matrix.target == 'frontend'
        run: yarn build
        env:
          CI: false
          DISABLE_ESLINT_PLUGIN: true
          
      - name: Build Storybook
        if: matrix.target == 'storybook'
        run: yarn build-storybook
        
      - name: Deploy ${{ matrix.target }}
        run: |
          echo "Deploying ${{ matrix.target }} to ${{ github.event.inputs.environment }}"
          echo "This is a placeholder for actual deployment commands"
          echo "Configure your deployment provider here (Vercel, Netlify, etc.)"
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-${{ github.event.inputs.environment }}-${{ github.sha }}
          path: |
            ${{ matrix.target == 'frontend' && 'build/' || 'storybook-static/' }}
          retention-days: 7