name: Health Monitor

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  health:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Check Production Health (optional)
        env:
          HEALTH_URL: ${{ secrets.RENDER_HEALTH_URL }}
        shell: bash
        run: |
          set -euo pipefail
          if [[ -z "${HEALTH_URL:-}" ]]; then
            echo "No production HEALTH_URL configured; skipping"
            exit 0
          fi
          CODE=$(curl -fsS -o /dev/null -w "%{http_code}" --max-time 10 "$HEALTH_URL" || true)
          echo "prod_status=$CODE" >> "$GITHUB_OUTPUT"
          echo "Production health status: $CODE"

      - name: Check Staging Health (optional)
        env:
          HEALTH_URL: ${{ secrets.RENDER_STAGING_HEALTH_URL }}
        shell: bash
        run: |
          set -euo pipefail
          if [[ -z "${HEALTH_URL:-}" ]]; then
            echo "No staging HEALTH_URL configured; skipping"
            exit 0
          fi
          CODE=$(curl -fsS -o /dev/null -w "%{http_code}" --max-time 10 "$HEALTH_URL" || true)
          echo "staging_status=$CODE" >> "$GITHUB_OUTPUT"
          echo "Staging health status: $CODE"

